name: "Bug Report"
description: "Signaler un bug dans l'application RoadBook"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de nous aider à améliorer RoadBook !
        Veuillez fournir autant d'informations que possible pour nous aider à reproduire et corriger le bug.

  - type: input
    id: contact
    attributes:
      label: Contact (email)
      description: "Si nous avons besoin de vous contacter pour clarifier le problème."
      placeholder: "example@email.com"
      default: "HE202326@students.ephec.be"

  - type: textarea
    id: what-happened
    attributes:
      label: Description du bug
      description: "Décrivez ce que vous avez observé"
      placeholder: "Ex: L'app crash lorsque je clique sur 'Partager un trajet'"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: "Listez les étapes pour reproduire le bug"
      placeholder: |
        1. Aller dans '...'
        2. Cliquer sur '...'
        3. Observez '...'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version de l'app
      description: "Quelle version de RoadBook utilisez-vous ?"
      placeholder: "v1.2.3"

  - type: dropdown
    id: platform
    attributes:
      label: Plateforme
      description: "Où le bug s’est-il produit ?"
      options:
        - Android
        - iOS
        - Web
        - Autre
