blank_issues_enabled: false
contact_links:
  - name: Signaler un bug critique
    url: https://github.com/Ajkll/testingroad/issues/new?assignees=&labels=bug&template=bug_report.yml&title=BUG%20critique%20-%20
    about: Utilisez ce lien pour signaler un bug urgent via le template officiel.
