version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=roadbook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all"]

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/roadbook
      - JWT_SECRET=your-very-secure-jwt-secret-for-development
      - JWT_REFRESH_SECRET=your-very-secure-refresh-token-secret-for-development
      - PORT=4000
      - NODE_ENV=development
      - CORS_ORIGINS=http://localhost:19000,http://localhost:19006,http://localhost:3000,exp://localhost:19000,https://haep9vw-anonymous-8081.exp.direct,https://*.exp.direct,exp://*-*.exp.direct,exp://*
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always

volumes:
  postgres_data:
    name: roadbook-postgres-data