version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-prod
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=roadbook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - roadbook-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server-prod
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/roadbook
      - JWT_SECRET=${JWT_SECRET:-your-very-secure-jwt-secret-for-production}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your-very-secure-refresh-token-secret-for-production}
      - PORT=4000
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=roadbook
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:19000,http://localhost:19006,http://localhost:3000,exp://localhost:19000}
    volumes:
      - server_logs:/app/logs
    restart: always
    networks:
      - roadbook-network
    command: ["npm", "run", "start"]

networks:
  roadbook-network:
    name: roadbook-network

volumes:
  postgres_data:
    name: roadbook-postgres-prod-data
  server_logs:
    name: roadbook-server-logs