name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock
      - name: Install dependencies
        run: |
          cd client
          yarn install --frozen-lockfile
      - name: Create lint directory
        run: mkdir -p client/lint-results
      - name: Run ESLint and generate reports
        run: |
          cd client
          # Toujours générer le rapport même en cas d'erreur
          yarn eslint --format html --output-file ./lint-results/report.html . || true
          # Afficher les erreurs dans les logs mais ne pas faire échouer le job
          yarn eslint --format stylish . || echo "ESLint found errors but continuing..."
      - name: Verify and upload report
        run: |
          cd client
          if [ -f "./lint-results/report.html" ]; then
            echo "ESLint report generated successfully"
            exit 0
          else
            echo "Failed to generate ESLint report"
            exit 1
          fi
      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: client/lint-results/report.html
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          cd client
          yarn install --frozen-lockfile
          cd ../server
          yarn install --frozen-lockfile
      - name: Run client tests with coverage
        run: |
          cd client
          yarn test:coverage || echo "::warning::Coverage insufficient"
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: client/coverage/lcov-report/
          if-no-files-found: warn
      - name: Run server tests
        run: |
          cd server
          yarn test