name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd client
          npm ci
      - name: Run linting and generate report
        run: |
          cd client
          mkdir -p lint-results
          eslint --format json --output-file lint-results/report.json . || true
      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: client/lint-results/
          if-no-files-found: warn

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd client
          npm ci
          cd ../server
          npm ci
      - name: Run client tests with coverage
        run: |
          cd client
          npm run test:coverage || echo "::warning::Coverage insufficient"
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: client/coverage/lcov-report/
          if-no-files-found: warn
      - name: Run server tests
        run: |
          cd server
          npm test