name: Test Env Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - test-env

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install -g eas-cli

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Configure Expo token
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          echo "EXPO_TOKEN configured as environment variable"
          eas whoami

      # Vérifier l'existence des fichiers app.json ou app.config.js
      - name: Check app config
        run: |
          if [ -f "app.json" ]; then
            echo "app.json exists"
            cat app.json
          elif [ -f "app.config.js" ]; then
            echo "app.config.js exists"
            cat app.config.js
          else
            echo "No app configuration found!"
            ls -la
          fi

      # Utiliser directement l'API EAS submit pour déclencher un build
      - name: Submit build directly to EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          mkdir -p build
          
          # Créer un fichier temporaire de keystore vide pour satisfaire la vérification
          mkdir -p android/keystores
          touch android/keystores/release.keystore
          
          echo '{"android":{"keystore":{"keystorePath":"android/keystores/release.keystore","keystorePassword":"placeholder","keyAlias":"placeholder","keyPassword":"placeholder"}}}' > ./android-credentials.json
          
          eas build --platform android --profile production \
            --non-interactive \
            --no-wait \
            --skip-credentials-check \
            --local-build-artifact-path "./build/app.aab" \
            --output-file "./build/app.aab"

      # Continuer avec le reste du workflow
      - name: Convert AAB to APK
        run: |
          echo "Converting AAB to APK..."
          wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
          java -jar bundletool-all-1.15.6.jar build-apks \
            --bundle=./build/app.aab \
            --output=./build/app.apks \
            --mode=universal
          unzip ./build/app.apks -d ./build
          mv ./build/universal.apk ./build/app.apk

      - name: Extract changelog entry
        id: changelog
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          SECTION=$(awk -v tag="$CURRENT_TAG" '
            BEGIN {found=0}
            /^## / {
              if ($0 ~ "\\["tag"\\]") {found=1; next}
              else if ($0 ~ /^## \[[0-9]+\.[0-9]+\.[0-9]+\]/) {found=0}
            }
            found {print}
          ' client/CHANGELOG.md)
          
          if [ -z "$SECTION" ]; then
            SECTION=$(cat client/CHANGELOG.md)
          fi
          
          CLEAN_SECTION=$(echo "$SECTION" | sed '/^$/d')
          
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$CLEAN_SECTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release with Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "v${{ github.ref_name }} (Test Env)"
          body: |
            ### Version ${{ github.ref_name }} (Test Environment)
            
            <details>
            <summary>Dernières modifications</summary>
            
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            
            </details>
            
            **Artifacts disponibles:**
            - Roadbook.apk (Android Package)
            - Roadbook.aab (Android App Bundle)
            
            [Voir le CHANGELOG complet](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/client/CHANGELOG.md)
          prerelease: true
          files: |
            build/app.apk
            build/app.aab

      - name: Create PR to main
        if: github.ref == 'refs/heads/test-env' && !contains(github.event.head_commit.message, 'chore(release)')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: test-env
          title: "Merge test-env → main (v${{ github.ref_name }})"
          body: |
            ### Nouvelles modifications dans test-env
            
            **Version:** ${{ github.ref_name }}
            **Artifacts:** [Voir la release](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }})
            
            <details>
            <summary>Dernières modifications</summary>
            
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            
            </details>
          labels: "automated-pr,needs-review"