name: Test Package Only

on:
  push:
    branches:
      - test-env

jobs:
  package_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          mkdir -p build
          mkdir -p ./client/credentials/android

      # Simulation de l'artefact du build
      - name: Setup test artifacts
        run: |
          # Créer un fichier app.aab simulé si nécessaire pour les tests
          echo "Creating test app.aab file"
          dd if=/dev/zero of=./build/app.aab bs=1M count=10
          
          # Créer un keystore simulé pour les tests
          echo "Creating test keystore.jks file"
          dd if=/dev/zero of=./client/credentials/android/keystore.jks bs=1K count=2
          
          echo "Prepared test artifacts:"
          ls -la build/
          ls -la ./client/credentials/android/

      - name: Debug file structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Files in build directory:"
          ls -la build
          echo "Files in credentials directory:"
          ls -la ./client/credentials/android/

      - name: Convert AAB to APK
        run: |
          if [ -f "./build/app.aab" ]; then
            echo "Found app.aab file, proceeding with conversion"
          
            # Télécharger bundletool
            wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
          
            # Vérifier que le keystore existe
            if [ ! -f "./client/credentials/android/keystore.jks" ]; then
              echo "ERROR: keystore.jks not found at expected path!"
              exit 1
            fi
          
            # Simuler la conversion pour les tests
            # Dans un environnement réel, la commande suivante serait utilisée:
            echo "Simulating APK conversion..."
            # java -jar bundletool-all-1.15.6.jar build-apks \
            #   --bundle=./build/app.aab \
            #   --output=./build/app.apks \
            #   --mode=universal \
            #   --ks=./client/credentials/android/keystore.jks \
            #   --ks-pass=pass:${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }} \
            #   --ks-key-alias=${{ secrets.EXPO_ANDROID_KEY_ALIAS }} \
            #   --key-pass=pass:${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
          
            # Simuler la création d'un APK pour tests
            echo "Creating test APK file"
            dd if=/dev/zero of=./build/app.apk bs=1M count=8
          
            echo "APK conversion successful"
          else
            echo "ERROR: app.aab file not found in build directory!"
            find . -name "app.aab" -type f
            exit 1
          fi

      - name: Upload packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts
          path: |
            build/app.aab
            build/app.apk