name: Test Env Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - test-env

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install -g eas-cli

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # Étape critique: créer les credentials dans le bon répertoire
      - name: Create keystore credentials in the correct directory
        run: |
          # Créer le répertoire pour les credentials
          mkdir -p ./credentials/android
          
          # Décodage du keystore dans le bon emplacement
          echo '${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}' | base64 -d > ./credentials/android/keystore.jks
          
          # Créer le fichier credentials.json
          cat > ./credentials.json << EOF
          {
            "android": {
              "keystore": {
                "keystorePath": "./credentials/android/keystore.jks",
                "keystorePassword": "${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}",
                "keyAlias": "${{ secrets.EXPO_ANDROID_KEY_ALIAS }}",
                "keyPassword": "${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}"
              }
            }
          }
          EOF
          
          # Vérifier que le fichier existe
          ls -la ./credentials/android/keystore.jks

      - name: Build Android App Bundle
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          # Forcer la déconnexion pour éviter l'utilisation des credentials distants
          eas logout || true
          
          # Utiliser withoutCredentials via une option temporaire
          TMP_EAS_JSON=$(mktemp)
          jq '.build."local-production".android.withoutCredentials = true' eas.json > "$TMP_EAS_JSON"
          mv "$TMP_EAS_JSON" eas.json
          
          # Lancer le build avec les credentials locaux et ATTENDRE qu'il se termine (pas de --no-wait)
          eas build --platform android --profile local-production \
          --non-interactive \
          --output=./build \
          --clear-cache
          
          # Vérifier que les artefacts de build existent
          ls -la ./build

      - name: Prepare APK from AAB
        run: |
          mkdir -p ./build
          
          # Rechercher le fichier AAB dans le répertoire de build ou ailleurs
          AAB_PATH=$(find . -name "*.aab" -type f | head -n 1)
          if [ -n "$AAB_PATH" ]; then
            echo "Found AAB at: $AAB_PATH"
            # Si le fichier n'est pas déjà dans ./build, le copier
            if [[ "$AAB_PATH" != "./build/"* ]]; then
              cp "$AAB_PATH" ./build/app.aab
            else
              # Renommer si nécessaire
              if [[ "$AAB_PATH" != "./build/app.aab" ]]; then
                mv "$AAB_PATH" ./build/app.aab
              fi
            fi
          else
            echo "No AAB file found! Checking Android directories..."
            if [ -d "./android" ]; then
              find ./android -type f -name "*.aab" || echo "No AAB found in android directory"
            fi
            # Ne pas exit 1 ici, mais afficher un avertissement
            echo "WARNING: Could not find AAB file. APK generation might fail."
          fi
          
          # Vérifier si le fichier AAB existe avant de tenter la conversion
          if [ -f "./build/app.aab" ]; then
            # Convertir AAB en APK (via bundletool)
            wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
            java -jar bundletool-all-1.15.6.jar build-apks \
              --bundle=./build/app.aab \
              --output=./build/app.apks \
              --mode=universal
            unzip ./build/app.apks -d ./build
            mv ./build/universal.apk ./build/app.apk
            echo "Successfully converted AAB to APK"
          else
            echo "ERROR: Cannot convert AAB to APK because AAB file is missing"
            # Permet au workflow de continuer même sans APK
            touch ./build/app.apk.missing
          fi

      - name: Extract changelog entry
        id: changelog
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          SECTION=$(awk -v tag="$CURRENT_TAG" '
            BEGIN {found=0}
            /^## / {
              if ($0 ~ "\\["tag"\\]") {found=1; next}
              else if ($0 ~ /^## \[[0-9]+\.[0-9]+\.[0-9]+\]/) {found=0}
            }
            found {print}
          ' CHANGELOG.md)
          
          if [ -z "$SECTION" ]; then
            SECTION=$(cat CHANGELOG.md)
          fi
          
          CLEAN_SECTION=$(echo "$SECTION" | sed '/^$/d')
          
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$CLEAN_SECTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check artifacts before release
        run: |
          echo "Checking available artifacts:"
          ls -la ./build/
          
          # Vérifier si les artifacts critiques existent
          if [ -f "./build/app.aab" ]; then
            echo "AAB file found and ready for release"
          else
            echo "WARNING: No AAB file found for release"
          fi
          
          if [ -f "./build/app.apk" ]; then
            echo "APK file found and ready for release"
          elif [ -f "./build/app.apk.missing" ]; then
            echo "WARNING: APK generation was skipped"
            rm ./build/app.apk.missing
          else
            echo "WARNING: No APK file found for release"
          fi

      - name: Create Release with Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "v${{ github.ref_name }} (Test Env)"
          body: |
            ### Version ${{ github.ref_name }} (Test Environment)
            
            <details>
            <summary>Dernières modifications</summary>
            
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            
            </details>
            
            **Artifacts disponibles:**
            - Roadbook.apk (Android Package)
            - Roadbook.aab (Android App Bundle)
            
            [Voir le CHANGELOG complet](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md)
          prerelease: true
          files: |
            build/app.apk
            build/app.aab

      - name: Create PR to main
        if: github.ref == 'refs/heads/test-env' && !contains(github.event.head_commit.message, 'chore(release)')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: test-env
          title: "Merge test-env → main (v${{ github.ref_name }})"
          body: |
            ### Nouvelles modifications dans test-env
            
            **Version:** ${{ github.ref_name }}
            **Artifacts:** [Voir la release](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }})
            
            <details>
            <summary>Dernières modifications</summary>
            
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            
            </details>
          labels: "automated-pr,needs-review"