name: Test Package Only

on:
  push:
    branches:
      - test-env

jobs:
  package_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download already built artifact
        run: |
          mkdir -p build
          # Téléchargement de l'artefact depuis l'URL GitHub
          ARTIFACT_URL="https://github.com/Ajkll/testingroad/actions/runs/14832439690/artifacts/3060736967"
          
          # Utiliser le token GitHub pour télécharger l'artifact
          echo "Downloading artifact from $ARTIFACT_URL"
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "$ARTIFACT_URL/zip" -o artifact.zip
          
          # Décompresser l'artifact
          unzip -o artifact.zip -d ./build_downloaded
          echo "Contents of downloaded artifact:"
          find ./build_downloaded -type f | sort
          
          # Copier les fichiers nécessaires
          cp -r ./build_downloaded/* ./build/
          echo "Files in build directory after copy:"
          find ./build -type f | sort

      # Alternative si le téléchargement direct ne fonctionne pas
      - name: Alternative - Use artifact from previous run
        if: ${{ failure() }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Test Env Release
          workflow_conclusion: success
          name: build-artifacts
          path: ./build
          skip_unpack: false

      - name: Debug file structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Files in build directory:"
          ls -la build || echo "Build directory not found"
          find . -name "app.aab" -type f || echo "app.aab not found"
          find . -name "keystore.jks" -type f || echo "keystore.jks not found"

      - name: Ensure keystore directory
        run: |
          mkdir -p ./client/credentials/android
          
          # Essayer de trouver le keystore et le copier
          KEYSTORE_PATH=$(find . -name "keystore.jks" -type f | head -n 1)
          
          if [ -n "$KEYSTORE_PATH" ]; then
            echo "Found keystore at $KEYSTORE_PATH"
            cp "$KEYSTORE_PATH" ./client/credentials/android/keystore.jks
          else
            echo "No keystore found!"
            exit 1
          fi

      - name: Convert AAB to APK
        run: |
          # Trouver le fichier app.aab où qu'il soit
          AAB_PATH=$(find . -name "app.aab" -type f | head -n 1)
          
          if [ -n "$AAB_PATH" ]; then
            echo "Found app.aab at $AAB_PATH"
            # Créer le répertoire de sortie si nécessaire
            mkdir -p build
          
            # Copier le fichier app.aab dans le répertoire build si nécessaire
            if [ "$AAB_PATH" != "./build/app.aab" ]; then
              cp "$AAB_PATH" "./build/app.aab"
            fi
          
            # Télécharger bundletool
            wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
          
            # Vérifier que le keystore existe
            if [ ! -f "./client/credentials/android/keystore.jks" ]; then
              echo "ERROR: keystore.jks not found at expected path!"
              exit 1
            fi
          
            # Convertir AAB en APK
            java -jar bundletool-all-1.15.6.jar build-apks \
              --bundle=./build/app.aab \
              --output=./build/app.apks \
              --mode=universal \
              --ks=./client/credentials/android/keystore.jks \
              --ks-pass=pass:${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }} \
              --ks-key-alias=${{ secrets.EXPO_ANDROID_KEY_ALIAS }} \
              --key-pass=pass:${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
          
            # Extraire et renommer l'APK
            unzip ./build/app.apks -d ./build
            mv ./build/universal.apk ./build/app.apk
            echo "APK conversion successful"
          else
            echo "ERROR: app.aab file not found!"
            exit 1
          fi

      - name: Upload packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts
          path: |
            build/app.aab
            build/app.apk