name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - test-env  # Déclenché aussi sur push direct vers test-env

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: test-env  # Checkout spécifique de test-env
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Get Version Info
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG_VERSION=$(node -p "require('./package.json').version" | sed 's/^v//')" >> $GITHUB_OUTPUT
          fi
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.TAG_VERSION }}
          release_name: "v${{ steps.version.outputs.TAG_VERSION }} (Test Env)"
          body: |
            Version test : ${{ steps.version.outputs.TAG_VERSION }}
            Branch: ${{ steps.version.outputs.BRANCH }}
            Changelog disponible dans CHANGELOG.md
          draft: false
          prerelease: true  # Marqué comme pré-release

      - name: Create PR to main
        if: github.ref == 'refs/heads/test-env' && !startsWith(github.ref, 'refs/tags/')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          delete-branch: false
          title: "Merge test-env to main (v${{ steps.version.outputs.TAG_VERSION }})"
          body: "Auto-generated PR from test-env branch"
          labels: "automated-pr,test-release"