name: Test Env Release

on:
  push:
    branches:
      - test-env  # Déclenché sur push direct vers test-env (sans tag)
    tags:
      - 'v*'      # Déclenché sur création de tag

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Extract Version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          fi

      # Étape Release (seulement pour les tags)
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.TAG_VERSION }}
          release_name: "v${{ steps.version.outputs.TAG_VERSION }} (Test Env)"
          body: "Pré-release depuis test-env. Changelog: ./CHANGELOG.md"
          draft: false
          prerelease: true

      # Étape PR (seulement pour les pushes directs sur test-env SANS tag)
      - name: Create PR to main
        if: github.ref == 'refs/heads/test-env' && !contains(github.event.head_commit.message, 'chore(release)')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: test-env
          title: "Merge test-env → main (v${{ steps.version.outputs.TAG_VERSION }})"
          body: |
            **Ne pas merger avant validation complète**
            - [ ] Tests validés
            - [ ] Revue UX nécessaire
          labels: "automated-pr,needs-review"
          assignees: "Ajkll"