name: Test Env Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - test-env

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install -g eas-cli

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # On n'utilise pas la commande login explicitement car EXPO_TOKEN est déjà dans l'environnement
      # et sera utilisé automatiquement par EAS

      # Étape critique: créer le keystore.json et la structure de répertoires
      - name: Create keystore.json credentials file
        run: |
          mkdir -p ./android/app/build/outputs/bundle/release
          mkdir -p ./android/keystores
          echo '${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}' | base64 -d > ./android/keystores/release.keystore
          cat > ./android/keystores/keystore.json << EOF
          {
            "keystore": "./release.keystore",
            "keystorePassword": "${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}",
            "keyAlias": "${{ secrets.EXPO_ANDROID_KEY_ALIAS }}",
            "keyPassword": "${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}"
          }
          EOF

      - name: Build Android App Bundle
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --profile local-production \
          --non-interactive \
          --no-wait \
          --clear-cache \
          --local \
          --local-build-options="--android-keystore-path=./credentials/android/keystore.jks"

      - name: Wait for build completion and download artifacts
        run: |
          # Pour un build local, l'attente n'est pas nécessaire, et l'artifact est déjà présent
          mkdir -p ./build
          find ./android -name "*.aab" -type f
          cp ./android/app/build/outputs/bundle/release/app-release.aab ./build/app.aab || echo "AAB file not found at expected location"
          
          # Si le fichier n'existe pas, cherchons-le
          if [ ! -f ./build/app.aab ]; then
            echo "Searching for AAB file..."
            AAB_PATH=$(find ./android -name "*.aab" -type f | head -n 1)
            if [ -n "$AAB_PATH" ]; then
              echo "Found AAB at: $AAB_PATH"
              cp "$AAB_PATH" ./build/app.aab
            else
              echo "No AAB file found!"
              exit 1
            fi
          fi
          
          # Convertir AAB en APK (via bundletool)
          wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
          java -jar bundletool-all-1.15.6.jar build-apks \
            --bundle=./build/app.aab \
            --output=./build/app.apks \
            --mode=universal
          unzip ./build/app.apks -d ./build
          mv ./build/universal.apk ./build/app.apk

      - name: Extract changelog entry
        id: changelog
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          SECTION=$(awk -v tag="$CURRENT_TAG" '
            BEGIN {found=0}
            /^## / {
              if ($0 ~ "\\["tag"\\]") {found=1; next}
              else if ($0 ~ /^## \[[0-9]+\.[0-9]+\.[0-9]+\]/) {found=0}
            }
            found {print}
          ' client/CHANGELOG.md)
          
          if [ -z "$SECTION" ]; then
            SECTION=$(cat client/CHANGELOG.md)
          fi
          
          CLEAN_SECTION=$(echo "$SECTION" | sed '/^$/d')
          
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$CLEAN_SECTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release with Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "v${{ github.ref_name }} (Test Env)"
          body: |
            ### Version ${{ github.ref_name }} (Test Environment)
            
            <details>
            <summary>Dernières modifications</summary>
            
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            
            </details>
            
            **Artifacts disponibles:**
            - Roadbook.apk (Android Package)
            - Roadbook.aab (Android App Bundle)
            
            [Voir le CHANGELOG complet](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/client/CHANGELOG.md)
          prerelease: true
          files: |
            build/app.apk
            build/app.aab

      - name: Create PR to main
        if: github.ref == 'refs/heads/test-env' && !contains(github.event.head_commit.message, 'chore(release)')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: test-env
          title: "Merge test-env → main (v${{ github.ref_name }})"
          body: |
            ### Nouvelles modifications dans test-env
            
            **Version:** ${{ github.ref_name }}
            **Artifacts:** [Voir la release](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }})
            
            <details>
            <summary>Dernières modifications</summary>
            
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            
            </details>
          labels: "automated-pr,needs-review"