name: Test Env Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - test-env

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Extract latest changelog entry
        id: changelog
        run: |
          # Get current tag version (without 'v' prefix)
          CURRENT_VERSION=${GITHUB_REF#refs/tags/v}
          
          # Extract the corresponding changelog section
          SECTION=$(awk -v version="$CURRENT_VERSION" '
            BEGIN {print = 0}
            /^## / {
              if ($2 == "["version"]") {print = 1; next}
              else if ($2 ~ /^\[[0-9]+\.[0-9]+\.[0-9]+\]/) {print = 0}
            }
            print && !/^## / {print $0}
          ' client/CHANGELOG.md)
          
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$SECTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "v${{ github.ref_name }} (Test Env)"
          body: |
            ### Version ${{ github.ref_name }} (Test Environment)
            
            <details>
            <summary>Dernières modifications (cliquez pour déplier)</summary>
            
            ```markdown
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            ```
            
            </details>
            
            [ Voir le CHANGELOG complet](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/client/CHANGELOG.md)
            
            ---
            *Release automatique générée le ${{ github.event.head_commit.timestamp }}*
          draft: false
          prerelease: true

      - name: Create PR to main
        if: github.ref == 'refs/heads/test-env' && !contains(github.event.head_commit.message, 'chore(release)')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: test-env
          title: "Merge test-env → main (v${{ github.ref_name }})"
          body: |
            ### Nouvelles modifications dans test-env
            
            **Version:** ${{ github.ref_name }}
            **Statut:** Pré-release
            
            <details>
            <summary>Dernières modifications</summary>
            
            ```markdown
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            ```
            
            </details>
            
            [Voir le diff complet](https://github.com/${{ github.repository }}/compare/main...test-env)
            
            ---
            *Ne pas merger avant validation complète*
          labels: "automated-pr,needs-review"