name: Test Env Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - test-env

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          yarn global add eas-cli

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock

      - name: Install dependencies
        run: |
          cd client
          yarn install

      - name: Create keystore credentials
        run: |
          cd client
          mkdir -p ./credentials/android
          echo '${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}' | base64 -d > ./credentials/android/keystore.jks
          cat > ./credentials.json << EOF
          {
            "android": {
              "keystore": {
                "keystorePath": "./credentials/android/keystore.jks",
                "keystorePassword": "${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}",
                "keyAlias": "${{ secrets.EXPO_ANDROID_KEY_ALIAS }}",
                "keyPassword": "${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}"
              }
            }
          }
          EOF

      - name: Build with EAS
        id: eas-build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          cd client
          
          # Méthode officielle pour l'authentification en CI
          echo "Setting up Expo token..."
          export EXPO_CLI_PREVIEW_AUTH_TOKEN=$EXPO_TOKEN
          
          # Alternative plus récente (valeur identique)
          export EXPO_TOKEN=$EXPO_TOKEN
          
          # Vérification de la connexion
          echo "Verifying authentication..."
          npx expo whoami || (echo " Expo authentication failed" && exit 1)
          
          # Configuration EAS
          echo " Configuring EAS project..."
          npx eas-cli build:configure --platform android
          
          # Build EAS
          echo " Starting EAS build..."
          npx eas-cli build \
            --platform android \
            --non-interactive \
            --no-wait \
            --json | tee eas-build.log
          
          # Récupération de l'ID du build
          BUILD_ID=$(jq -r '.buildId' eas-build.log)
          echo "Build ID: ${BUILD_ID}"
          echo "build_id=${BUILD_ID}" >> $GITHUB_OUTPUT
          
          echo "EAS build started successfully. Check progress at https://expo.dev/accounts/ajkll/projects/Roadbook/builds"

      - name: Local build for GitHub artifacts
        run: |
          cd client
          if [ ! -d "./android" ]; then
            yarn expo prebuild --platform android --clean
          fi
          
          cd android
          ./gradlew bundleRelease
          
          mkdir -p ../../build
          AAB_PATH=$(find . -name "*.aab" -type f | grep -v intermediates | head -n 1)
          [ -n "$AAB_PATH" ] && cp "$AAB_PATH" ../../build/app.aab || exit 1

      - name: Convert AAB to APK
        run: |
          if [ -f "./build/app.aab" ]; then
            wget https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
            # Using keystore to sign the APK during conversion
            java -jar bundletool-all-1.15.6.jar build-apks \
              --bundle=./build/app.aab \
              --output=./build/app.apks \
              --mode=universal \
              --ks=./client/credentials/android/keystore.jks \
              --ks-pass=pass:${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }} \
              --ks-key-alias=${{ secrets.EXPO_ANDROID_KEY_ALIAS }} \
              --key-pass=pass:${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
            unzip ./build/app.apks -d ./build
            mv ./build/universal.apk ./build/app.apk
          else
            echo "ERROR: app.aab file not found!"
            exit 1
          fi

      - name: Extract changelog entry
        id: changelog
        run: |
          cd client
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          if [ -f "CHANGELOG.md" ]; then
            SECTION=$(awk -v tag="$CURRENT_TAG" '
              BEGIN {found=0}
              /^## / {
                if ($0 ~ "\\["tag"\\]") {found=1; next}
                else if ($0 ~ /^## \[[0-9]+\.[0-9]+\.[0-9]+\]/) {found=0}
              }
              found {print}
            ' CHANGELOG.md)
            [ -z "$SECTION" ] && SECTION=$(cat CHANGELOG.md)
          else
            SECTION="Pas de CHANGELOG.md trouvé pour cette version."
          fi
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$SECTION" | sed '/^$/d' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          # Debug output
          echo "Extracted changelog content:"
          echo "$SECTION"

      - name: Create Release with Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "v${{ github.ref_name }} (Test Env)"
          body: |
            ### Version ${{ github.ref_name }} (Test Environment)
            
            <details>
            <summary>Dernières modifications</summary>
            
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            
            </details>
            
            **Artifacts disponibles:**
            - Roadbook.apk (Android Package)
            - Roadbook.aab (Android App Bundle)
            
            [Voir le CHANGELOG complet](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/client/CHANGELOG.md)
          prerelease: true
          files: |
            build/app.apk
            build/app.aab

      - name: Setup Git identity
        if: github.ref == 'refs/heads/test-env'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clean sensitive files before PR
        if: github.ref == 'refs/heads/test-env'
        run: |
          cd client
          rm -f credentials.json
          rm -rf credentials
          git add .
          git diff --staged --quiet || git commit -m "Remove sensitive files before PR"

      - name: Create PR to main
        if: github.ref == 'refs/heads/test-env' && !contains(github.event.head_commit.message, 'chore(release)')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: test-env-to-main # This parameter was 'head' before, changed to 'branch'
          title: "Merge test-env → main (v${{ github.ref_name }})"
          body: |
            ### Nouvelles modifications dans test-env
            
            **Version:** ${{ github.ref_name }}
            **Artifacts:** [Voir la release](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }})
            
            <details>
            <summary>Dernières modifications</summary>
            
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
            
            </details>
          labels: "automated-pr,needs-review"
          commit-message: "chore: merge test-env to main [skip ci]"